name: E2E Test Matrix Runner

on:
  # Schedule nightly runs
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day

jobs:
  matrix-runner:
    strategy:
      fail-fast: false
      matrix:
        arkd-version: [
          '6246f89716f7795801c2d453a02ec911898c4e15',
          'master',
          'next-version'
          # Add more versions as needed
        ]

    uses: ./.github/workflows/e2e-core.yml
    with:
      arkd-version: ${{ matrix.arkd-version }}
